# Numpy Indexing

In [1]:
import numpy as np

In [2]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr.shape

(11,)

In [6]:
arr[5]

5

In [7]:
arr[2:6]

array([2, 3, 4, 5])

In [8]:
arr[100]

IndexError: index 100 is out of bounds for axis 0 with size 11

In [9]:
arr[2:100]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

# Brodcasting

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[2:5]

array([2, 3, 4])

In [12]:
arr[2:5]=65

In [13]:
arr

array([ 0,  1, 65, 65, 65,  5,  6,  7,  8,  9, 10])

In [14]:
arr=np.arange(0,11)

In [15]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr2=arr[2:5]

In [17]:
arr2

array([2, 3, 4])

In [18]:
arr2[1:2]=56

In [19]:
arr2

array([ 2, 56,  4])

In [20]:
arr2

array([ 2, 56,  4])

In [21]:
arr

array([ 0,  1,  2, 56,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr=np.arange(0,11)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr_copy=arr.copy()

In [25]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing of 2D array

In [26]:
arr2d=np.array(([5,10,15],[20,25,30],[35,40,45]))

In [27]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr2d[2]

array([35, 40, 45])

In [29]:
arr2d[:,2]

array([15, 30, 45])

In [30]:
arr2d[0]

array([ 5, 10, 15])

In [31]:
arr2d[1]

array([20, 25, 30])

In [32]:
arr2d[:,1]

array([10, 25, 40])

In [33]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr2d[1,0]

20

In [35]:
arr2d[2,2]

45

In [36]:
arr2d[1,1]

25

In [37]:
arr2d[1,2]

30

In [38]:
arr2d[1,1:]

array([25, 30])

In [39]:
arr2d[0:2,1]

array([10, 25])

In [40]:
arr2d[1:,2]

array([30, 45])

In [41]:
arr2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr2d[1,:]

array([20, 25, 30])

In [44]:
arr2d[1:2]

array([[20, 25, 30]])

In [45]:
arr2d[1]

array([20, 25, 30])

# Fancy Indexing

In [49]:
arr2d=np.zeros((10,10),dtype=int)

In [50]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [56]:
for i in range(10):
    arr2d[i]=i
print(arr2d)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]


In [57]:
for i in arr2d:
    arr2d[i]=i
print(arr2d)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]


In [59]:
arr2d[[1,3,5,7,9]]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

# Selections

In [60]:
arr=np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [64]:
arr[arr<9]

array([1, 2, 3, 4, 5, 6, 7, 8])

# Numpy Operation

In [65]:
arr=np.arange(0,10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
arr/arr

<ipython-input-70-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/arr

<ipython-input-71-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [72]:
10/arr

<ipython-input-72-1a20ae47604a>:1: RuntimeWarning: divide by zero encountered in true_divide
  10/arr


array([        inf, 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [76]:
np.max(arr)

9

In [77]:
np.min(arr)

0

In [78]:
np.log(arr)

<ipython-input-78-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [79]:
np.log(10)

2.302585092994046

In [80]:
arr=np.zeros(10)

In [81]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
np.ones(10)+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [84]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [87]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [89]:
arr=[[0,1,2],[3,4,5],[6,7,8]]

In [88]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [100]:
#arr[arr%2==0]

In [101]:
arr

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [103]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
np.array(arr)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
np.random.rand(1)

array([0.03681297])

In [107]:
np.random.rand()

0.44650046017683476

In [108]:
np.random.rand(25)

array([0.75514602, 0.50696728, 0.73800626, 0.93185611, 0.84404783,
       0.42572895, 0.65693159, 0.50819821, 0.35752111, 0.87096424,
       0.53288242, 0.53411825, 0.93643921, 0.52735568, 0.00511375,
       0.73100838, 0.55242971, 0.54209972, 0.72122899, 0.63217267,
       0.01227652, 0.68494855, 0.70222006, 0.47506754, 0.51315739])

In [109]:
np.random.randn(25)

array([-1.43128249,  0.87225902,  0.86136993,  0.45610351, -1.5428111 ,
        0.37550113,  0.32099071,  2.67067342,  2.11789146, -0.16870122,
        0.93220185,  0.79958287, -1.92819266,  0.88030674,  0.36481012,
       -0.34024738, -0.65841642,  0.17212001,  2.26455908, -0.04423204,
        0.25384623, -0.55738879, -0.57540583, -0.45271102, -0.66627615])

In [132]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [138]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [147]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [148]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [149]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [150]:
arr=np.arange(1,26).reshape(5,5)

In [151]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [152]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [153]:
arr[3,4]

20

In [154]:
arr[:3,1]

array([ 2,  7, 12])

In [156]:
arr[:3,1].reshape(1,3)

array([[ 2,  7, 12]])

In [158]:
arr[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [159]:
arr[4]

array([21, 22, 23, 24, 25])

In [160]:
arr[4:,:]

array([[21, 22, 23, 24, 25]])

In [161]:
arr[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [163]:
arr[1,0]

6

In [164]:
arr[3,3]

19

In [170]:
arr[1,0],arr[3,3]

(6, 19)