# Numpy

In [2]:
# Linear Algebra Library
# Fast

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

# Numpy Arrays

In [5]:
list1=[20,40,50,70,90]

In [6]:
type(list1)

list

In [7]:
arr1=np.array(list1)

In [8]:
arr1

array([20, 40, 50, 70, 90])

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
type(arr1)

numpy.ndarray

In [11]:
seq=[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
seq

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
arr2=np.array(seq)

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.ones(10,dtype=int)*10

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [22]:
np.ones(10,dtype=int)+5

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [23]:
np.ones(10,dtype=int)-1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [27]:
np.full(10,300)

array([300, 300, 300, 300, 300, 300, 300, 300, 300, 300])

In [29]:
np.ones((5,5))*3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

# Linspace

In [30]:
#Equal Space or Specific Intervals

In [31]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [32]:
np.linspace(1,20,30)

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

# Identity Matrix

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.rand(5)

array([0.64721791, 0.20460523, 0.52679658, 0.59356977, 0.94401939])

In [36]:
np.random.rand(5,5)

array([[0.35718274, 0.94821281, 0.71961273, 0.90301019, 0.94063172],
       [0.62607791, 0.11908133, 0.67589561, 0.54191948, 0.11114495],
       [0.43192258, 0.74747878, 0.35744798, 0.66227414, 0.9739551 ],
       [0.9189727 , 0.02054276, 0.39259232, 0.90302027, 0.58670827],
       [0.15986647, 0.64606185, 0.65666733, 0.89787283, 0.59459516]])

In [37]:
np.random.randn(5)

array([-0.33455929,  1.0308122 , -0.23796766, -0.08872247,  0.1586818 ])

In [38]:
np.random.randn(5,5)

array([[ 2.40049828, -0.41444979,  1.82754281, -0.33332012,  2.24648402],
       [-0.54871267, -0.94788388, -0.04473128,  1.35421057,  0.73323315],
       [-0.91837222,  0.49480868,  0.99446935,  1.9740202 , -0.23802706],
       [ 0.39830567,  0.18664828,  0.09605477, -0.40462784, -0.64564199],
       [-0.02152036, -0.24563394,  0.36291903, -0.31283806, -1.27582457]])

In [39]:
np.random.randint(5)

0

In [40]:
np.random.randint(5)

3

In [68]:
np.random.randint(5,10)

7

In [73]:
np.random.randint(1,100,10)

array([38, 50, 13, 78, 53, 86, 86, 75, 22, 84])

In [75]:
arr=np.arange(25)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arr.shape

(25,)

In [80]:
arr2d=arr.reshape(5,5)

In [81]:
arr2d.shape

(5, 5)

In [82]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
arr2d.shape[1]        # for Column

5

In [86]:
arr2d.shape[0]

5

In [87]:
arr=arr2d

In [88]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
arr[0:,1]

array([ 1,  6, 11, 16, 21])

In [90]:
arr[0:,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [91]:
arr.max()

24

In [92]:
arr.min()

0

In [93]:
np.max(arr)

24

In [94]:
np.min(arr)

0

In [95]:
arr.dtype

dtype('int32')