In [1]:
import numpy as np

In [2]:
arr=np.arange(1,26).reshape(5,5)

In [3]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
arr[1,0],arr[3,3]

(6, 19)

In [7]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [8]:
arr[3,4]

20

In [12]:
(arr[0:3,1:2])

array([[ 2],
       [ 7],
       [12]])

In [13]:
arr[4:]

array([[21, 22, 23, 24, 25]])

In [14]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
arr[1,0],arr[3,3]

(6, 19)

In [22]:
arr[[1,3],[0,3]]

array([ 6, 19])

In [27]:
arr[[0,4],[4,0]]

array([ 5, 21])

In [28]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr.sum()

325

In [31]:
arr.sum(0)

array([55, 60, 65, 70, 75])

In [32]:
arr.sum(1)

array([ 15,  40,  65,  90, 115])

In [34]:
arr.std()

7.211102550927978

In [37]:
arr.sum(1)

array([ 15,  40,  65,  90, 115])

In [38]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
arr[0:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [40]:
pwd

'C:\\Users\\Adesh\\Desktop\\Python, DS and ML'

In [41]:
import os

In [42]:
os.getcwd()

'C:\\Users\\Adesh\\Desktop\\Python, DS and ML'