# Pandas

Introduction to Pandas

In [2]:
import pandas as pd

In [3]:
!pip install pandas

# Series

In [4]:
import numpy as np

In [5]:
labels=['a','b','c','d','e']

In [6]:
labels

['a', 'b', 'c', 'd', 'e']

In [7]:
type(labels)

list

In [8]:
my_list=[100,200,300,400,500]

In [9]:
my_list

[100, 200, 300, 400, 500]

In [11]:
arr=np.array([1000,2000,3000,4000,5000])

In [12]:
arr

array([1000, 2000, 3000, 4000, 5000])

In [13]:
type(arr)

numpy.ndarray

In [14]:
d={'p':101,'q':102,'r':103,'s':104,'t':105}

In [15]:
d

{'p': 101, 'q': 102, 'r': 103, 's': 104, 't': 105}

In [16]:
type(d)

dict

In [17]:
labels

['a', 'b', 'c', 'd', 'e']

In [18]:
my_list

[100, 200, 300, 400, 500]

In [19]:
arr

array([1000, 2000, 3000, 4000, 5000])

In [20]:
d

{'p': 101, 'q': 102, 'r': 103, 's': 104, 't': 105}

In [21]:
pd.Series(data=my_list)

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [23]:
pd.Series(data=my_list,index=labels)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [24]:
pd.Series(arr)

0    1000
1    2000
2    3000
3    4000
4    5000
dtype: int32

In [25]:
d

{'p': 101, 'q': 102, 'r': 103, 's': 104, 't': 105}

In [27]:
pd.Series(d)

p    101
q    102
r    103
s    104
t    105
dtype: int64

In [28]:
pd.Series(d,arr)

1000   NaN
2000   NaN
3000   NaN
4000   NaN
5000   NaN
dtype: float64

In [29]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [34]:
ser1=pd.Series([10,20,30,40],index=['Mumbai','Pune','Banglore','Chennai'])

In [35]:
ser2=pd.Series([10,20,50,40],index=['Mumbai','Pune','Delhi','Chennai'])

In [36]:
ser1

Mumbai      10
Pune        20
Banglore    30
Chennai     40
dtype: int64

In [37]:
ser2

Mumbai     10
Pune       20
Delhi      50
Chennai    40
dtype: int64

In [39]:
ser1+ser2

Banglore     NaN
Chennai     80.0
Delhi        NaN
Mumbai      20.0
Pune        40.0
dtype: float64

In [40]:
type(ser1)

pandas.core.series.Series

In [41]:
type(ser2)

pandas.core.series.Series

# DataFrames

In [44]:
np.random.randn()

-0.5786986418803604

In [45]:
np.random.randn(5,4)

array([[-0.33905783,  0.08739947,  0.05078005, -0.08959694],
       [-0.11999676, -0.60079565,  0.00733227, -1.06494261],
       [ 0.29752962,  0.48777597, -0.96633611, -0.57595256],
       [ 0.96009959,  0.62042749,  0.98289418,  0.41700092],
       [-1.34040053, -1.82989089, -0.34236814,  0.69185406]])

In [47]:
from numpy.random import randn

In [48]:
randn(5,4)

array([[-0.77054088,  1.02637213,  1.09999551, -1.20811108],
       [ 0.69660032, -0.82070314, -0.42961961, -0.16917741],
       [ 0.29679768, -1.80559975, -0.4750547 ,  0.25120146],
       [-0.03690338, -0.71955963,  0.40551464, -1.4458168 ],
       [-0.16063801,  0.77160145, -0.45200713, -0.0632424 ]])

In [49]:
np.random.randn(5,4)

array([[ 0.13104082,  2.15273999,  1.51799405, -0.02371094],
       [ 0.48332884, -0.59451825,  1.10684668,  0.60413576],
       [-0.29829311,  0.80081078, -0.24442577, -0.86282893],
       [ 0.15245976,  0.6582499 ,  1.49894163,  2.04832075],
       [-0.40267139, -0.51011683, -0.17616617, -0.51731234]])

In [50]:
np.random.seed(101)

In [51]:
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [52]:
np.random.seed(101)

In [53]:
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [54]:
np.random.seed(101)

In [55]:
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [56]:
np.random.seed(101)

In [57]:
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [58]:
np.random.randn(5)

array([ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072])

In [59]:
np.random.randn(5)

array([0.39052784, 0.16690464, 0.18450186, 0.80770591, 0.07295968])

In [60]:
np.random.seed(30)

In [61]:
np.random.randn(5)

array([-1.26405266,  1.52790535, -0.97071094,  0.47055962, -0.10069672])

In [62]:
np.random.seed(30)

In [63]:
np.random.randn(5)

array([-1.26405266,  1.52790535, -0.97071094,  0.47055962, -0.10069672])

In [64]:
np.random.randn(5)

array([ 0.30379318, -1.72596243,  1.58509537,  0.13429659, -1.10685547])

In [69]:
df=pd.DataFrame(data=np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [70]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305




Selection and Indexing in the form of Dataset

In [71]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [72]:
df['W']

A   -1.100144
B   -0.689229
C   -0.701402
D   -0.029193
E    1.898881
Name: W, dtype: float64

In [77]:
df[['W','Z']]

W         Z
A -1.100144 -1.044778
B -0.689229 -1.921170
C -0.701402 -0.536874
D -0.029193  1.019127
E  1.898881 -1.927305

In [78]:
type(df[['W','Z']])

pandas.core.frame.DataFrame

In [80]:
df[['X','Z']]

X         Z
A -1.315644 -1.044778
B -0.852757 -1.921170
C  0.849088 -0.536874
D  1.394056  1.019127
E -0.354850 -1.927305

In [81]:
df[['W','Y','Z']]

W         Y         Z
A -1.100144  0.810501 -1.044778
B -0.689229  1.113472 -1.921170
C -0.701402  1.050700 -0.536874
D -0.029193 -0.397867  1.019127
E  1.898881 -0.387016 -1.927305

In [82]:
df['W']

A   -1.100144
B   -0.689229
C   -0.701402
D   -0.029193
E    1.898881
Name: W, dtype: float64

In [83]:
df.W

A   -1.100144
B   -0.689229
C   -0.701402
D   -0.029193
E    1.898881
Name: W, dtype: float64

In [84]:
df['NEW_COLUMN']=df['X']+df['Z']

In [85]:
df['NEW_COLUMN']

A   -2.360422
B   -2.773927
C    0.312213
D    2.413183
E   -2.282155
Name: NEW_COLUMN, dtype: float64

In [86]:
df

W         X         Y         Z  NEW_COLUMN
A -1.100144 -1.315644  0.810501 -1.044778   -2.360422
B -0.689229 -0.852757  1.113472 -1.921170   -2.773927
C -0.701402  0.849088  1.050700 -0.536874    0.312213
D -0.029193  1.394056 -0.397867  1.019127    2.413183
E  1.898881 -0.354850 -0.387016 -1.927305   -2.282155

In [87]:
df.drop("NEW_COLUMN",axis=1)

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [88]:
df

W         X         Y         Z  NEW_COLUMN
A -1.100144 -1.315644  0.810501 -1.044778   -2.360422
B -0.689229 -0.852757  1.113472 -1.921170   -2.773927
C -0.701402  0.849088  1.050700 -0.536874    0.312213
D -0.029193  1.394056 -0.397867  1.019127    2.413183
E  1.898881 -0.354850 -0.387016 -1.927305   -2.282155

In [89]:
df.drop("NEW_COLUMN",axis=1,inplace=True)

In [90]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [91]:
df.drop("D",axis=0)

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
E  1.898881 -0.354850 -0.387016 -1.927305

In [92]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [93]:
df.loc['B']

W   -0.689229
X   -0.852757
Y    1.113472
Z   -1.921170
Name: B, dtype: float64

In [94]:
df.loc['D']

W   -0.029193
X    1.394056
Y   -0.397867
Z    1.019127
Name: D, dtype: float64

In [95]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [96]:
df.iloc[2]

W   -0.701402
X    0.849088
Y    1.050700
Z   -0.536874
Name: C, dtype: float64

In [97]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [99]:
df.loc['B','Y']

1.113472107571644

In [100]:
df.loc[['B','C'],['W','Z']]

W         Z
B -0.689229 -1.921170
C -0.701402 -0.536874

In [101]:
df.loc[['B','C'],['W','X','Z']]

W         X         Z
B -0.689229 -0.852757 -1.921170
C -0.701402  0.849088 -0.536874

In [102]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [103]:
df>0

W      X      Y      Z
A  False  False   True  False
B  False  False   True  False
C  False   True   True  False
D  False   True  False   True
E   True  False  False  False

In [104]:
df[df>0]

W         X         Y         Z
A       NaN       NaN  0.810501       NaN
B       NaN       NaN  1.113472       NaN
C       NaN  0.849088  1.050700       NaN
D       NaN  1.394056       NaN  1.019127
E  1.898881       NaN       NaN       NaN

In [105]:
df['W']

A   -1.100144
B   -0.689229
C   -0.701402
D   -0.029193
E    1.898881
Name: W, dtype: float64

In [106]:
df['W']>0

A    False
B    False
C    False
D    False
E     True
Name: W, dtype: bool

In [107]:
df[df['W']>0]

W        X         Y         Z
E  1.898881 -0.35485 -0.387016 -1.927305

In [108]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [109]:
df[df['W']>0]['Z']

E   -1.927305
Name: Z, dtype: float64

In [111]:
df[df['W']>0][['X','Z']]

X         Z
E -0.35485 -1.927305

In [114]:
(df['W']>0) & (df['Y']>0)

A    False
B    False
C    False
D    False
E    False
dtype: bool

In [115]:
df

W         X         Y         Z
A -1.100144 -1.315644  0.810501 -1.044778
B -0.689229 -0.852757  1.113472 -1.921170
C -0.701402  0.849088  1.050700 -0.536874
D -0.029193  1.394056 -0.397867  1.019127
E  1.898881 -0.354850 -0.387016 -1.927305

In [116]:
df[(df['W']>0) & (df['Y']>0)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [117]:
df.reset_index()

index         W         X         Y         Z
0     A -1.100144 -1.315644  0.810501 -1.044778
1     B -0.689229 -0.852757  1.113472 -1.921170
2     C -0.701402  0.849088  1.050700 -0.536874
3     D -0.029193  1.394056 -0.397867  1.019127
4     E  1.898881 -0.354850 -0.387016 -1.927305

In [118]:
newind='MI CSK RCB DC SRH'.split()

In [119]:
newind

['MI', 'CSK', 'RCB', 'DC', 'SRH']

In [120]:
df['cities']=newind

In [121]:
df

W         X         Y         Z cities
A -1.100144 -1.315644  0.810501 -1.044778     MI
B -0.689229 -0.852757  1.113472 -1.921170    CSK
C -0.701402  0.849088  1.050700 -0.536874    RCB
D -0.029193  1.394056 -0.397867  1.019127     DC
E  1.898881 -0.354850 -0.387016 -1.927305    SRH

In [122]:
df.set_index('cities')

W         X         Y         Z
cities                                        
MI     -1.100144 -1.315644  0.810501 -1.044778
CSK    -0.689229 -0.852757  1.113472 -1.921170
RCB    -0.701402  0.849088  1.050700 -0.536874
DC     -0.029193  1.394056 -0.397867  1.019127
SRH     1.898881 -0.354850 -0.387016 -1.927305

In [123]:
df

W         X         Y         Z cities
A -1.100144 -1.315644  0.810501 -1.044778     MI
B -0.689229 -0.852757  1.113472 -1.921170    CSK
C -0.701402  0.849088  1.050700 -0.536874    RCB
D -0.029193  1.394056 -0.397867  1.019127     DC
E  1.898881 -0.354850 -0.387016 -1.927305    SRH

In [124]:
df.set_index('cities',inplace=True)

In [125]:
df

W         X         Y         Z
cities                                        
MI     -1.100144 -1.315644  0.810501 -1.044778
CSK    -0.689229 -0.852757  1.113472 -1.921170
RCB    -0.701402  0.849088  1.050700 -0.536874
DC     -0.029193  1.394056 -0.397867  1.019127
SRH     1.898881 -0.354850 -0.387016 -1.927305

In [126]:
outside=['G1','G1','G1','G2','G2','G2']

In [128]:
inside=[1,2,3,1,2,3]

In [132]:
h1=list(zip(outside,inside))

In [133]:
h1

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [134]:
hier_index=pd.MultiIndex.from_tuples(h1)

In [135]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [136]:
df2=pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [137]:
df2

A         B
G1 1  0.550757  0.954356
   2  0.782777 -1.793238
   3  1.241855  1.707747
G2 1  0.323153 -0.991834
   2 -1.163282 -0.021335
   3 -1.581995 -1.243114

In [139]:
df2.loc['G1']

A         B
1  0.550757  0.954356
2  0.782777 -1.793238
3  1.241855  1.707747

In [140]:
df2.loc['G1'].loc[2]

A    0.782777
B   -1.793238
Name: 2, dtype: float64

In [141]:
df2.index.names

FrozenList([None, None])

In [142]:
df2.index.names=['Group','Number']

In [143]:
df2

A         B
Group Number                    
G1    1       0.550757  0.954356
      2       0.782777 -1.793238
      3       1.241855  1.707747
G2    1       0.323153 -0.991834
      2      -1.163282 -0.021335
      3      -1.581995 -1.243114

In [144]:
df2.xs('G1')

A         B
Number                    
1       0.550757  0.954356
2       0.782777 -1.793238
3       1.241855  1.707747

In [145]:
df2.xs(['G1',2])

A    0.782777
B   -1.793238
Name: (G1, 2), dtype: float64

In [146]:
df2.xs(2,level='Number')

A         B
Group                    
G1     0.782777 -1.793238
G2    -1.163282 -0.021335

In [147]:
df2

A         B
Group Number                    
G1    1       0.550757  0.954356
      2       0.782777 -1.793238
      3       1.241855  1.707747
G2    1       0.323153 -0.991834
      2      -1.163282 -0.021335
      3      -1.581995 -1.243114